### ISSUE TITLE
Blank page returned while trying to display Saltpad

### ISSUE THREAD

**Issue by aanriot** [Lothiraldan/saltpad#143]
Hello,

I have cloned the Saltpad Git repository and setup salt-api (rest_tornado) as advised.

When I try to access the GUI, I get a blank page, either with index-dev.html or index-prod.html.

Though, I can see in the source:

```html
<!doctype html>
<html lang="en" data-framework="react">
	<head>
		<meta charset="utf-8">
		<title>SaltPad</title>
	</head>
	<body>
		<div id="app"></div>
	</body>
</html>
```

I'm using Debian 8.3 and Nginx 1.6.2.

Could you tell me how I can get logs and debug informations?

Thanks.

**Comment by Lothiraldan** [comment]
Hello @aanriot,

on what URL do you tries to access SaltPad? Did you serve it via npm run?

From what I can see, you tried to open directly the index-dev.html from your browser which will not works because it doesn't link to the javascript code.

You need either try a release version of saltpad which index.html is understandable by the browser directly and with all required files or follow this part of documentation to build a nightly version and serve it locally: https://github.com/Lothiraldan/saltpad#hack-on-saltpad.

Saltpad actually require a develop version (should change very soon) of salt-api, so a docker-compose environment is provided, you can follow this README https://github.com/Lothiraldan/saltpad/blob/master/README_DOCKER.md to launch the docker-compose environnement.

You should be able to test saltpad with theses instructions.

**Comment by aanriot** [comment]
Hello @Lothiraldan,

Thanks for the reply. I have tried using Docker and the container startup ends with:

```code
npm info it worked if it ends with ok
npm info using npm@3.7.3
npm info using node@v5.9.0
npm info lifecycle saltpad@~prestart: saltpad@
npm info lifecycle saltpad@~start: saltpad@

> saltpad@ start /usr/src/app
> node devServer.js

Listening at http://0.0.0.0:3333
webpack built db85d4e632476e6060c7 in 19572ms
```

When trying to access it, I get redirected to /login but the web interface is still blank though.

**Comment by Lothiraldan** [comment]
The redirection to /login is a good sign, it means the the javascript code runned. Could you please open your browser debug console and paste me any error message? Could you also give me your browser version?

**Comment by aanriot** [comment]
Hello @Lothiraldan,

I'm using Firefox 45.0.1 on MacOS.

Here is what I can see on the console:

```code
"Download the React DevTools for a better development experience:
  https://fb.me/react-devtools" ReactDOM.js:66:9
/!\ mutating the [[Prototype]] of an object will cause your code to run very slowly;
  instead create the object with the correct initial [[Prototype]] value using Object.create
  app.js line 1739 > eval:11:415
[HMR] connected
```

If I refresh the page:

```code
La connexion avec http://XXXXXX:3333/__webpack_hmr a été interrompue pendant le chargement de 
  la page. app.js line 581 > eval:41:15
/!\ "Download the React DevTools for a better development experience:
  https://fb.me/react-devtools" 
  ReactDOM.js:66:9
[HMR] connected client.js:55:22
mutating the [[Prototype]] of an object will cause your code to run very slowly;
instead create the object with the correct initial [[Prototype]] value using Object.create
```

Thanks.

**Comment by aanriot** [comment]
Hello @Lothiraldan,

Have you been able to check my last message?

Thanks.

**Comment by aanriot** [comment]
Hello,

I gave up a few days ago, thanks.

Cheers,

**Comment by abacuspix** [comment]
hello @@Lothiraldan,
I also encounter this issue.
Blank page returned while trying to display Saltpad

1. docker build -t name/saltpad:latest .    
2. docker run -p 3333:3333 name/saltpad:latest
after that also return the black package.
Also I got the exception from the chrome in console

for react-transform-catch-errors does not look like a React component.');
